sources = 1.c 2.c test.c
objects = $(patsubst %.c,%.o,$(sources))
print:
	echo abspath=$(abspath ../socket)
	echo $(sources)
	echo $(objects)
	echo $(sources)
	echo obj=$(patsubst %.c,%.o,$(sources))


